trigger:
  - master

name: $(Build.BuildId)

pool:
  name: 'Default'

steps:
  - script: |
      set -e # abort script if any command fails
      npm ci
      npm run lint
      npm run build
    displayName: 'NPM Install and Build'
